apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://0.0.0.0:43173
  name: k3d-conversao-temperatura
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://0.0.0.0:34213
  name: k3d-kube-news
contexts:
- context:
    cluster: k3d-conversao-temperatura
    user: admin@k3d-conversao-temperatura
  name: k3d-conversao-temperatura
- context:
    cluster: k3d-kube-news
    user: admin@k3d-kube-news
  name: k3d-kube-news
current-context: k3d-kube-news
kind: Config
preferences: {}
users:
- name: admin@k3d-conversao-temperatura
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
- name: admin@k3d-kube-news
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED